### ISSUE TITLE
No Data from TTGO in Android App rdzSondyGO

### ISSUE THREAD

**Issue by smarti2019** [dl9rdz/rdz_ttgo_sonde#68]
With the current version, data from a received radiosonde is no longer displayed in the Android app. However, the connection to the TTGO is established. This Problem exist since Version from 14 and 15 March.

**Comment by dl9rdz** [comment]
Thanks. fixed.

**Comment by LukePrior** [comment]
Where can I find this app?

**Comment by LukePrior** [comment]
I downloaded v1.0.5 but I'm not sure how to connect, both devices are on the same network is AP mode required?

**Comment by vanThijs** [comment]
I have the same issue with v1.0.5 and the rdzSondyGo app: No connection between the App and the TTGO.

**Comment by LukePrior** [comment]
> I have the same issue with v1.0.5 and the rdzSondyGo app: No connection between the App and the TTGO.

The app started working for me once the device had detected a Sonde.

**Comment by vanThijs** [comment]
And how was it configured: was the ttgo in AP mode, or connected to an infrastructure WiFi network?

**Comment by LukePrior** [comment]
> And how was it configured: was the ttgo in AP mode, or connected to an infrastructure WiFi network?

The two devices were both connected to the same network.

**Comment by dl9rdz** [comment]
It has to be the same network.
Either TTGO in AP mode and smartphone connected to that AP (tricky if you want internet access for the map at the same time)
Or TTGO and smartphone connected to the same external access point (without firewall. some "guest" networks of access points limit IP traffic)
Or Smartphone as AP (tethering) and TTGO connected to the Smartphone AP (probably the most suitable configuration for mobile use)
All variants should work.

**Comment by vanThijs** [comment]
Thank you for the clarification!

**Comment by pavolgaj** [comment]
I have the same issue with the latest development firmware and Android app as mentioned by @smarti2019. App shows TTGO as connected (green icon), but no data received from sonde is displayed.
The Master version of rdzTTGO works fine.

**Comment by dl9rdz** [comment]
Ok, thanks for reporting this.

The latest devel version has some changes to the JSON exporter code, this might be the cause of this problem. Will have a look at it the next days...

**Comment by dl9rdz** [comment]
Should be fixed in the  update  today

**Comment by pavolgaj** [comment]
It still doesn't work. App (in info window) shows green circle = data from the radiosonde. But, displayed data are default values of the app (e.g. sonde id is A123456).

**Comment by dl9rdz** [comment]
Which version of the app are you using? 
I was testing with v1.0.6, and this seemed to be working fine here.

**Comment by pavolgaj** [comment]
I have also v1.0.6. And tested with standard RS41 sonde.

**Comment by dl9rdz** [comment]
Hmm. That is strange. That is exactly my test setup here. devel20220414 , app 1.0.6, and a RS41. 

In case you have Android tools installed, you could put your phone in USB debug mode, run "adb logcat" and send me the output

**Comment by pavolgaj** [comment]
I found the reason for my problem. I test it inside - therefore sonde hasn't GPS data. And probably TTGO doesn't send a JSON string for incomplete data.
When I put sonde outside and got the position, App shows the correct information.

In the previous version of firmware, I tested it always inside without a similar problem. You maybe implemented some additional filtering for uploading data to App.
